steps:
  # Step 1: Set up Docker and build the image from the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/flask-app:${SHORT_SHA}', '.']
  
  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/flask-app:${SHORT_SHA}']

  # Step 3: Deploy the image to the Compute Engine instance by restarting the Docker container
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - '--zone=${ZONE}'
      - '--project=${PROJECT_ID}'
      - '--command=gcloud compute instances describe jashan-backend-vm --zone=${ZONE} --project=${PROJECT_ID} && docker pull gcr.io/${PROJECT_ID}/flask-app:${SHORT_SHA} && docker stop flask-container && docker rm flask-container && docker run -d --name flask-container -p 5000:5000 gcr.io/${PROJECT_ID}/flask-app:${SHORT_SHA}'
    env:
      - 'CLOUDSDK_CORE_PROJECT=${PROJECT_ID}'
    id: 'deploy-to-instance'

images:
  - 'gcr.io/${PROJECT_ID}/flask-app:${SHORT_SHA}'
