substitutions:
  PRIVATE_KEY: 'gcloud secrets versions access 1 --secret="my-ssh-private-key" --format="get(payload.data)" | tr "_-" "/+" | base64 -d'

steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA}', '.']

  # Step 2: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA}']

  # Step 3: SSH into Compute Engine and update the container
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    env:
      - 'PRIVATE_KEY=$(gcloud secrets versions access 1 --secret="my-ssh-private-key" --format="get(payload.data)" | tr "_-" "/+" | base64 -d)'
    args:
      - '-c'
      - |
        # Save the private key to a file
        echo "$PRIVATE_KEY" > /workspace/id_rsa
        chmod 600 /workspace/id_rsa

        # Add SSH key to known hosts
        ssh-keyscan -H jashan-backend-vm >> ~/.ssh/known_hosts

        echo "Updating backend container on Compute Engine..."
        # SSH into the Compute Engine instance and update the Docker container
        gcloud compute ssh jashan-backend-vm \
          --zone=us-central1-a \
          --ssh-key-file=/workspace/id_rsa \
          --command=" 
            sudo docker stop backend-container || true && \
            sudo docker rm backend-container || true && \
            sudo docker pull us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA} && \
            sudo docker run -d -p 5000:5000 --name backend-container us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA}
          "

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA}'
