steps:
  # Step 0: Configure docker to use gcloud credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'configure-docker', 'us-central1-docker.pkg.dev']

  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA}', '.']

  # Step 2: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA}']

  # Step 3: Setup SSH and deploy to VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    secretEnv: ['PRIVATE_KEY', 'PUBLIC_KEY']
    args:
      - '-e'  # Exit on error
      - '-c'
      - |
        # Create SSH directory
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        # Decode and save SSH keys
        echo "$$PRIVATE_KEY" > ~/.ssh/id_rsa.b64
        base64 --decode ~/.ssh/id_rsa.b64 > ~/.ssh/id_rsa 2>/dev/null
        echo "$$PUBLIC_KEY" > ~/.ssh/id_rsa.pub.b64
        base64 --decode ~/.ssh/id_rsa.pub.b64 > ~/.ssh/id_rsa.pub 2>/dev/null

        # Set correct permissions
        chmod 600 ~/.ssh/id_rsa
        chmod 644 ~/.ssh/id_rsa.pub

        # Get instance IP address
        INSTANCE_IP=$(gcloud compute instances describe jashan-backend-vm \
          --zone=us-central1-a \
          --format='get(networkInterfaces[0].accessConfigs[0].natIP)')

        # Add instance IP to known hosts
        ssh-keyscan -H "$INSTANCE_IP" > ~/.ssh/known_hosts 2>/dev/null

        # Deploy using gcloud compute ssh
        gcloud compute ssh jashan-backend-vm \
          --zone=us-central1-a \
          --project=eng-oven-435418-i5 \
          --ssh-key-file=~/.ssh/id_rsa \
          --strict-host-key-checking=no \
          --quiet \
          --command="docker pull us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA} && \
                    docker stop backend-container || true && \
                    docker rm backend-container || true && \
                    docker run -d --name backend-container -p 5000:5000 \
                      us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA}"

availableSecrets:
  secretManager:
    - versionName: projects/851164891096/secrets/my-ssh-private-key/versions/3
      env: 'PRIVATE_KEY'
    - versionName: projects/851164891096/secrets/my-public-ssh-key/versions/2
      env: 'PUBLIC_KEY'

images:
  - 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
