steps:
  # Step 0: Configure docker to use gcloud credentials
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'configure-docker', 'us-central1-docker.pkg.dev']

  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA}', '.']

  # Step 2: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA}']

  # Step 3: SSH into Compute Engine and update the container
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    secretEnv: ['PRIVATE_KEY', 'PUBLIC_KEY']
    args:
      - '-c'
      - |
        # Setup SSH keys
        echo "$$PRIVATE_KEY" | base64 -d > /workspace/id_rsa
        echo "$$PUBLIC_KEY" | base64 -d > /workspace/id_rsa.pub
        chmod 600 /workspace/id_rsa
        chmod 644 /workspace/id_rsa.pub
        
        # Setup SSH configuration
        mkdir -p ~/.ssh
        
        # Get the VM's IP and store in a variable
        export VM_IP=$(gcloud compute instances describe jashan-backend-vm --zone=us-central1-a --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
        
        # Add VM's IP to known hosts
        if [ -n "$VM_IP" ]; then
          ssh-keyscan -H "$VM_IP" >> ~/.ssh/known_hosts
        else
          echo "Failed to get VM IP address"
          exit 1
        fi
        
        echo "Updating backend container on Compute Engine..."
        gcloud compute ssh jashan-backend-vm \
          --zone=us-central1-a \
          --ssh-key-file=/workspace/id_rsa \
          --strict-host-key-checking=no \
          --project=eng-oven-435418-i5 \
          --command="sudo docker stop backend-container || true && \
                    sudo docker rm backend-container || true && \
                    sudo docker pull us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA} && \
                    sudo docker run -d -p 5000:5000 --name backend-container us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA}"

availableSecrets:
  secretManager:
    - versionName: projects/851164891096/secrets/my-ssh-private-key/versions/3
      env: 'PRIVATE_KEY'
    - versionName: projects/851164891096/secrets/my-public-ssh-key/versions/1
      env: 'PUBLIC_KEY'

images:
  - 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-backend-repo/jashan-backend:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
